KIND_FIELD = "kind"
LOW_POSITION = "low"
HIGH_POSITION = "high"
ENERGY_FIELD = "energy"

LNCRNA_FIELD = "lncRNA"
MIRNA_FIELD = "miRNA"
PAIR_FIELDS = [LNCRNA_FIELD, MIRNA_FIELD]
IS_POSITIVE_FIELD = "positive"
PRECURSOR_FIELD = "precursor"
MATURE_FIELD = "mature"
